///////////////////////////////////////////////////////////////////////////////
// CAUTION: This file was auto-generated by `dotnet build -t:GenerateISOCurrencies`.
//          Changes to this file will be lost when the file is regenerated.
///////////////////////////////////////////////////////////////////////////////

namespace NetCash

module ISOCurrencyCodes =

    /// Andorran Franc
    [<Literal>]
    let ADF = "ADF"

    /// Andorran Peseta
    [<Literal>]
    let ADP = "ADP"

    /// UAE Dirham
    [<Literal>]
    let AED = "AED"

    /// Afghani
    [<Literal>]
    let AFA = "AFA"

    /// Afghani
    [<Literal>]
    let AFN = "AFN"

    /// Lek
    [<Literal>]
    let ALL = "ALL"

    /// Armenian Dram
    [<Literal>]
    let AMD = "AMD"

    /// Netherlands Antillian Guilder
    [<Literal>]
    let ANG = "ANG"

    /// Kwanza
    [<Literal>]
    let AOA = "AOA"

    /// Angola New Kwanza
    [<Literal>]
    let AON = "AON"

    /// Angola Kwanza Reajustado
    [<Literal>]
    let AOR = "AOR"

    /// Argentine Austral
    [<Literal>]
    let ARA = "ARA"

    /// Argentine Peso
    [<Literal>]
    let ARS = "ARS"

    /// Austrian Schilling
    [<Literal>]
    let ATS = "ATS"

    /// Australian Dollar
    [<Literal>]
    let AUD = "AUD"

    /// Aruban Guilder
    [<Literal>]
    let AWG = "AWG"

    /// Azerbaijanian Manat
    [<Literal>]
    let AZM = "AZM"

    /// Azerbaijanian Manat
    [<Literal>]
    let AZN = "AZN"

    /// Bosnia and Herzegovina Dinar
    [<Literal>]
    let BAD = "BAD"

    /// Convertible Marks
    [<Literal>]
    let BAM = "BAM"

    /// Barbados Dollar
    [<Literal>]
    let BBD = "BBD"

    /// Taka
    [<Literal>]
    let BDT = "BDT"

    /// Belgian Franc
    [<Literal>]
    let BEF = "BEF"

    /// Bulgarian Lev A/99
    [<Literal>]
    let BGL = "BGL"

    /// Bulgarian Lev
    [<Literal>]
    let BGN = "BGN"

    /// Bahraini Dinar
    [<Literal>]
    let BHD = "BHD"

    /// Burundi Franc
    [<Literal>]
    let BIF = "BIF"

    /// Bermudian Dollar
    [<Literal>]
    let BMD = "BMD"

    /// Brunei Dollar
    [<Literal>]
    let BND = "BND"

    /// Boliviano
    [<Literal>]
    let BOB = "BOB"

    /// Mvdol
    [<Literal>]
    let BOV = "BOV"

    /// Brazilian Cruzeiro
    [<Literal>]
    let BRE = "BRE"

    /// Brazilian Real
    [<Literal>]
    let BRL = "BRL"

    /// Brazilian Cruzeiro Real
    [<Literal>]
    let BRR = "BRR"

    /// Bahamian Dollar
    [<Literal>]
    let BSD = "BSD"

    /// Ngultrum
    [<Literal>]
    let BTN = "BTN"

    /// Pula
    [<Literal>]
    let BWP = "BWP"

    /// Belarussian Rouble
    [<Literal>]
    let BYB = "BYB"

    /// Belarussian Ruble
    [<Literal>]
    let BYR = "BYR"

    /// Belarussian Ruble
    [<Literal>]
    let BYN = "BYN"

    /// Belize Dollar
    [<Literal>]
    let BZD = "BZD"

    /// Canadian Dollar
    [<Literal>]
    let CAD = "CAD"

    /// Franc Congolais
    [<Literal>]
    let CDF = "CDF"

    /// WIR Euro
    [<Literal>]
    let CHE = "CHE"

    /// Swiss Franc
    [<Literal>]
    let CHF = "CHF"

    /// WIR Franc
    [<Literal>]
    let CHW = "CHW"

    /// Unidades de fomento
    [<Literal>]
    let CLF = "CLF"

    /// Chilean Peso
    [<Literal>]
    let CLP = "CLP"

    /// Yuan Renminbi
    [<Literal>]
    let CNY = "CNY"

    /// Colombian Peso
    [<Literal>]
    let COP = "COP"

    /// Unidad de Valor Real
    [<Literal>]
    let COU = "COU"

    /// Costa Rican Colon
    [<Literal>]
    let CRC = "CRC"

    /// Cuban Peso
    [<Literal>]
    let CUP = "CUP"

    /// Cuban Convertible Peso
    [<Literal>]
    let CUC = "CUC"

    /// Cape Verde Escudo
    [<Literal>]
    let CVE = "CVE"

    /// Cyprus Pound
    [<Literal>]
    let CYP = "CYP"

    /// Czech Koruna
    [<Literal>]
    let CZK = "CZK"

    /// Deutsche Mark
    [<Literal>]
    let DEM = "DEM"

    /// Djibouti Franc
    [<Literal>]
    let DJF = "DJF"

    /// Danish Krone
    [<Literal>]
    let DKK = "DKK"

    /// Dominican Peso
    [<Literal>]
    let DOP = "DOP"

    /// Algerian Dinar
    [<Literal>]
    let DZD = "DZD"

    /// Ecuador Sucre
    [<Literal>]
    let ECS = "ECS"

    /// Kroon
    [<Literal>]
    let EEK = "EEK"

    /// Egyptian Pound
    [<Literal>]
    let EGP = "EGP"

    /// Nakfa
    [<Literal>]
    let ERN = "ERN"

    /// Spanish Peseta
    [<Literal>]
    let ESP = "ESP"

    /// Ethiopian Birr
    [<Literal>]
    let ETB = "ETB"

    /// Euro
    [<Literal>]
    let EUR = "EUR"

    /// Finnish Markka
    [<Literal>]
    let FIM = "FIM"

    /// Fiji Dollar
    [<Literal>]
    let FJD = "FJD"

    /// Falkland Islands Pound
    [<Literal>]
    let FKP = "FKP"

    /// French Franc
    [<Literal>]
    let FRF = "FRF"

    /// Pound Sterling
    [<Literal>]
    let GBP = "GBP"

    /// Lari
    [<Literal>]
    let GEL = "GEL"

    /// Cedi
    [<Literal>]
    let GHC = "GHC"

    /// Ghana Cedi
    [<Literal>]
    let GHS = "GHS"

    /// Gibraltar Pound
    [<Literal>]
    let GIP = "GIP"

    /// Dalasi
    [<Literal>]
    let GMD = "GMD"

    /// Guinea Franc
    [<Literal>]
    let GNF = "GNF"

    /// Greek Drachma
    [<Literal>]
    let GRD = "GRD"

    /// Quetzal
    [<Literal>]
    let GTQ = "GTQ"

    /// Guinea-Bissau Peso
    [<Literal>]
    let GWP = "GWP"

    /// Guyana Dollar
    [<Literal>]
    let GYD = "GYD"

    /// Hong Kong Dollar
    [<Literal>]
    let HKD = "HKD"

    /// Lempira
    [<Literal>]
    let HNL = "HNL"

    /// Croatian Kuna
    [<Literal>]
    let HRK = "HRK"

    /// Gourde
    [<Literal>]
    let HTG = "HTG"

    /// Forint
    [<Literal>]
    let HUF = "HUF"

    /// Rupiah
    [<Literal>]
    let IDR = "IDR"

    /// Irish Pound
    [<Literal>]
    let IEP = "IEP"

    /// New Israeli Sheqel
    [<Literal>]
    let ILS = "ILS"

    /// Indian Rupee
    [<Literal>]
    let INR = "INR"

    /// Iraqi Dinar
    [<Literal>]
    let IQD = "IQD"

    /// Iranian Rial
    [<Literal>]
    let IRR = "IRR"

    /// Iceland Krona
    [<Literal>]
    let ISK = "ISK"

    /// Italian Lira
    [<Literal>]
    let ITL = "ITL"

    /// Jamaican Dollar
    [<Literal>]
    let JMD = "JMD"

    /// Jordanian Dinar
    [<Literal>]
    let JOD = "JOD"

    /// Yen
    [<Literal>]
    let JPY = "JPY"

    /// Kenyan Shilling
    [<Literal>]
    let KES = "KES"

    /// Som
    [<Literal>]
    let KGS = "KGS"

    /// Riel
    [<Literal>]
    let KHR = "KHR"

    /// Comoro Franc
    [<Literal>]
    let KMF = "KMF"

    /// North Korean Won
    [<Literal>]
    let KPW = "KPW"

    /// Won
    [<Literal>]
    let KRW = "KRW"

    /// Kuwaiti Dinar
    [<Literal>]
    let KWD = "KWD"

    /// Cayman Islands Dollar
    [<Literal>]
    let KYD = "KYD"

    /// Tenge
    [<Literal>]
    let KZT = "KZT"

    /// Kip
    [<Literal>]
    let LAK = "LAK"

    /// Lebanese Pound
    [<Literal>]
    let LBP = "LBP"

    /// Sri Lanka Rupee
    [<Literal>]
    let LKR = "LKR"

    /// Liberian Dollar
    [<Literal>]
    let LRD = "LRD"

    /// Loti
    [<Literal>]
    let LSL = "LSL"

    /// Lithuanian Litas
    [<Literal>]
    let LTL = "LTL"

    /// Luxembourg Franc
    [<Literal>]
    let LUF = "LUF"

    /// Latvian Lats
    [<Literal>]
    let LVL = "LVL"

    /// Libyan Dinar
    [<Literal>]
    let LYD = "LYD"

    /// Moroccan Dirham
    [<Literal>]
    let MAD = "MAD"

    /// Moldovan Leu
    [<Literal>]
    let MDL = "MDL"

    /// Malagasy Ariary
    [<Literal>]
    let MGA = "MGA"

    /// Malagasy Franc
    [<Literal>]
    let MGF = "MGF"

    /// Denar
    [<Literal>]
    let MKD = "MKD"

    /// Mali Franc
    [<Literal>]
    let MLF = "MLF"

    /// Kyat
    [<Literal>]
    let MMK = "MMK"

    /// Tugrik
    [<Literal>]
    let MNT = "MNT"

    /// Pataca
    [<Literal>]
    let MOP = "MOP"

    /// Ouguiya
    [<Literal>]
    let MRO = "MRO"

    /// Ouguiya
    [<Literal>]
    let MRU = "MRU"

    /// Maltese Lira
    [<Literal>]
    let MTL = "MTL"

    /// Mauritius Rupee
    [<Literal>]
    let MUR = "MUR"

    /// Rufiyaa
    [<Literal>]
    let MVR = "MVR"

    /// Kwacha
    [<Literal>]
    let MWK = "MWK"

    /// Mexican Peso
    [<Literal>]
    let MXN = "MXN"

    /// Mexican Unidad de Inversion (UDI)
    [<Literal>]
    let MXV = "MXV"

    /// Malaysian Ringgit
    [<Literal>]
    let MYR = "MYR"

    /// Mozambique Metical
    [<Literal>]
    let MZM = "MZM"

    /// Metical
    [<Literal>]
    let MZN = "MZN"

    /// Namibia Dollar
    [<Literal>]
    let NAD = "NAD"

    /// Naira
    [<Literal>]
    let NGN = "NGN"

    /// Nicaraguan Cordoba
    [<Literal>]
    let NIC = "NIC"

    /// Cordoba Oro
    [<Literal>]
    let NIO = "NIO"

    /// Netherlands Guilder
    [<Literal>]
    let NLG = "NLG"

    /// Norwegian Krone
    [<Literal>]
    let NOK = "NOK"

    /// Nepalese Rupee
    [<Literal>]
    let NPR = "NPR"

    /// New Zealand Dollar
    [<Literal>]
    let NZD = "NZD"

    /// Rial Omani
    [<Literal>]
    let OMR = "OMR"

    /// Balboa
    [<Literal>]
    let PAB = "PAB"

    /// Nuevo Sol
    [<Literal>]
    let PEN = "PEN"

    /// Kina
    [<Literal>]
    let PGK = "PGK"

    /// Philippine Peso
    [<Literal>]
    let PHP = "PHP"

    /// Pakistan Rupee
    [<Literal>]
    let PKR = "PKR"

    /// Zloty
    [<Literal>]
    let PLN = "PLN"

    /// Portuguese Escudo
    [<Literal>]
    let PTE = "PTE"

    /// Guarani
    [<Literal>]
    let PYG = "PYG"

    /// Qatari Rial
    [<Literal>]
    let QAR = "QAR"

    /// Romanian Old Leu
    [<Literal>]
    let ROL = "ROL"

    /// New Leu
    [<Literal>]
    let RON = "RON"

    /// Serbian Dinar
    [<Literal>]
    let RSD = "RSD"

    /// Russian Rouble
    [<Literal>]
    let RUB = "RUB"

    /// Rwanda Franc
    [<Literal>]
    let RWF = "RWF"

    /// Saudi Riyal
    [<Literal>]
    let SAR = "SAR"

    /// Solomon Islands Dollar
    [<Literal>]
    let SBD = "SBD"

    /// Seychelles Rupee
    [<Literal>]
    let SCR = "SCR"

    /// Sudanese Dinar
    [<Literal>]
    let SDD = "SDD"

    /// Sudanese Pound
    [<Literal>]
    let SDG = "SDG"

    /// Sudanese Pound
    [<Literal>]
    let SDP = "SDP"

    /// Swedish Krona
    [<Literal>]
    let SEK = "SEK"

    /// Singapore Dollar
    [<Literal>]
    let SGD = "SGD"

    /// Saint Helena Pound
    [<Literal>]
    let SHP = "SHP"

    /// Slovenian Tolar
    [<Literal>]
    let SIT = "SIT"

    /// Slovak Koruna
    [<Literal>]
    let SKK = "SKK"

    /// Leone
    [<Literal>]
    let SLL = "SLL"

    /// Somali Shilling
    [<Literal>]
    let SOS = "SOS"

    /// Surinam Dollar
    [<Literal>]
    let SRD = "SRD"

    /// Suriname Guilder
    [<Literal>]
    let SRG = "SRG"

    /// Dobra
    [<Literal>]
    let STD = "STD"

    /// El Salvador Colon
    [<Literal>]
    let SVC = "SVC"

    /// Syrian Pound
    [<Literal>]
    let SYP = "SYP"

    /// Lilangeni
    [<Literal>]
    let SZL = "SZL"

    /// Baht
    [<Literal>]
    let THB = "THB"

    /// Tajik Rouble
    [<Literal>]
    let TJR = "TJR"

    /// Somoni
    [<Literal>]
    let TJS = "TJS"

    /// Manat
    [<Literal>]
    let TMM = "TMM"

    /// Manat
    [<Literal>]
    let TMT = "TMT"

    /// Tunisian Dinar
    [<Literal>]
    let TND = "TND"

    /// Pa'anga
    [<Literal>]
    let TOP = "TOP"

    /// Turkish Lira
    [<Literal>]
    let TRY = "TRY"

    /// Trinidad and Tobago Dollar
    [<Literal>]
    let TTD = "TTD"

    /// New Taiwan Dollar
    [<Literal>]
    let TWD = "TWD"

    /// Tanzanian Shilling
    [<Literal>]
    let TZS = "TZS"

    /// Hryvnia
    [<Literal>]
    let UAH = "UAH"

    /// Uganda Shilling
    [<Literal>]
    let UGX = "UGX"

    /// US Dollar
    [<Literal>]
    let USD = "USD"

    /// US Dollar (Next day)
    [<Literal>]
    let USN = "USN"

    /// US Dollar (Same day)
    [<Literal>]
    let USS = "USS"

    /// Uruguay Peso en Unidades Indexadas
    [<Literal>]
    let UYI = "UYI"

    /// Peso Uruguayo
    [<Literal>]
    let UYU = "UYU"

    /// Uzbekistan Sum
    [<Literal>]
    let UZS = "UZS"

    /// Venezuela Bolívar
    [<Literal>]
    let VEB = "VEB"

    /// Bolivar Fuerte
    [<Literal>]
    let VEF = "VEF"

    /// Bolivar Soberano
    [<Literal>]
    let VES = "VES"

    /// Bolivar Soberano
    [<Literal>]
    let VED = "VED"

    /// Dong
    [<Literal>]
    let VND = "VND"

    /// Vatu
    [<Literal>]
    let VUV = "VUV"

    /// Tala
    [<Literal>]
    let WST = "WST"

    /// Yemeni Rial
    [<Literal>]
    let YER = "YER"

    /// Yugoslavian Dinar
    [<Literal>]
    let YUM = "YUM"

    /// Rand
    [<Literal>]
    let ZAR = "ZAR"

    /// Kwacha (old)
    [<Literal>]
    let ZMK = "ZMK"

    /// Zambian Kwacha
    [<Literal>]
    let ZMW = "ZMW"

    /// Zimbabwe Dollar
    [<Literal>]
    let ZWD = "ZWD"

    /// Zimbabwe Dollar
    [<Literal>]
    let ZWL = "ZWL"

    /// CFA Franc BEAC
    [<Literal>]
    let XAF = "XAF"

    /// East Caribbean Dollar
    [<Literal>]
    let XCD = "XCD"

    /// SDR
    [<Literal>]
    let XDR = "XDR"

    /// Gold-Franc
    [<Literal>]
    let XFO = "XFO"

    /// UIC-Franc
    [<Literal>]
    let XFU = "XFU"

    /// CFA Franc BCEAO
    [<Literal>]
    let XOF = "XOF"

    /// CFP Franc
    [<Literal>]
    let XPF = "XPF"

    /// Code for testing purposes
    [<Literal>]
    let XTS = "XTS"

    /// No currency
    [<Literal>]
    let XXX = "XXX"

    /// Silver
    [<Literal>]
    let XAG = "XAG"

    /// Gold
    [<Literal>]
    let XAU = "XAU"

    /// Palladium
    [<Literal>]
    let XPD = "XPD"

    /// Platinum
    [<Literal>]
    let XPT = "XPT"

    /// Sistema Unitario de Compensación Regional
    [<Literal>]
    let XSU = "XSU"

type ISOCurrencies internal (table) =
    /// Get currency by ISO code.
    member _.Item
        with get code =
            GnuCashObject.Registry.getOrCreate<Commodity> (
                Bindings.gnc_commodity_table_lookup (table, Bindings.GNC_COMMODITY_NS_CURRENCY, code)
            )

    /// Andorran Franc
    member self.ADF = self["ADF"]

    /// Andorran Peseta
    member self.ADP = self["ADP"]

    /// UAE Dirham
    member self.AED = self["AED"]

    /// Afghani
    member self.AFA = self["AFA"]

    /// Afghani
    member self.AFN = self["AFN"]

    /// Lek
    member self.ALL = self["ALL"]

    /// Armenian Dram
    member self.AMD = self["AMD"]

    /// Netherlands Antillian Guilder
    member self.ANG = self["ANG"]

    /// Kwanza
    member self.AOA = self["AOA"]

    /// Angola New Kwanza
    member self.AON = self["AON"]

    /// Angola Kwanza Reajustado
    member self.AOR = self["AOR"]

    /// Argentine Austral
    member self.ARA = self["ARA"]

    /// Argentine Peso
    member self.ARS = self["ARS"]

    /// Austrian Schilling
    member self.ATS = self["ATS"]

    /// Australian Dollar
    member self.AUD = self["AUD"]

    /// Aruban Guilder
    member self.AWG = self["AWG"]

    /// Azerbaijanian Manat
    member self.AZM = self["AZM"]

    /// Azerbaijanian Manat
    member self.AZN = self["AZN"]

    /// Bosnia and Herzegovina Dinar
    member self.BAD = self["BAD"]

    /// Convertible Marks
    member self.BAM = self["BAM"]

    /// Barbados Dollar
    member self.BBD = self["BBD"]

    /// Taka
    member self.BDT = self["BDT"]

    /// Belgian Franc
    member self.BEF = self["BEF"]

    /// Bulgarian Lev A/99
    member self.BGL = self["BGL"]

    /// Bulgarian Lev
    member self.BGN = self["BGN"]

    /// Bahraini Dinar
    member self.BHD = self["BHD"]

    /// Burundi Franc
    member self.BIF = self["BIF"]

    /// Bermudian Dollar
    member self.BMD = self["BMD"]

    /// Brunei Dollar
    member self.BND = self["BND"]

    /// Boliviano
    member self.BOB = self["BOB"]

    /// Mvdol
    member self.BOV = self["BOV"]

    /// Brazilian Cruzeiro
    member self.BRE = self["BRE"]

    /// Brazilian Real
    member self.BRL = self["BRL"]

    /// Brazilian Cruzeiro Real
    member self.BRR = self["BRR"]

    /// Bahamian Dollar
    member self.BSD = self["BSD"]

    /// Ngultrum
    member self.BTN = self["BTN"]

    /// Pula
    member self.BWP = self["BWP"]

    /// Belarussian Rouble
    member self.BYB = self["BYB"]

    /// Belarussian Ruble
    member self.BYR = self["BYR"]

    /// Belarussian Ruble
    member self.BYN = self["BYN"]

    /// Belize Dollar
    member self.BZD = self["BZD"]

    /// Canadian Dollar
    member self.CAD = self["CAD"]

    /// Franc Congolais
    member self.CDF = self["CDF"]

    /// WIR Euro
    member self.CHE = self["CHE"]

    /// Swiss Franc
    member self.CHF = self["CHF"]

    /// WIR Franc
    member self.CHW = self["CHW"]

    /// Unidades de fomento
    member self.CLF = self["CLF"]

    /// Chilean Peso
    member self.CLP = self["CLP"]

    /// Yuan Renminbi
    member self.CNY = self["CNY"]

    /// Colombian Peso
    member self.COP = self["COP"]

    /// Unidad de Valor Real
    member self.COU = self["COU"]

    /// Costa Rican Colon
    member self.CRC = self["CRC"]

    /// Cuban Peso
    member self.CUP = self["CUP"]

    /// Cuban Convertible Peso
    member self.CUC = self["CUC"]

    /// Cape Verde Escudo
    member self.CVE = self["CVE"]

    /// Cyprus Pound
    member self.CYP = self["CYP"]

    /// Czech Koruna
    member self.CZK = self["CZK"]

    /// Deutsche Mark
    member self.DEM = self["DEM"]

    /// Djibouti Franc
    member self.DJF = self["DJF"]

    /// Danish Krone
    member self.DKK = self["DKK"]

    /// Dominican Peso
    member self.DOP = self["DOP"]

    /// Algerian Dinar
    member self.DZD = self["DZD"]

    /// Ecuador Sucre
    member self.ECS = self["ECS"]

    /// Kroon
    member self.EEK = self["EEK"]

    /// Egyptian Pound
    member self.EGP = self["EGP"]

    /// Nakfa
    member self.ERN = self["ERN"]

    /// Spanish Peseta
    member self.ESP = self["ESP"]

    /// Ethiopian Birr
    member self.ETB = self["ETB"]

    /// Euro
    member self.EUR = self["EUR"]

    /// Finnish Markka
    member self.FIM = self["FIM"]

    /// Fiji Dollar
    member self.FJD = self["FJD"]

    /// Falkland Islands Pound
    member self.FKP = self["FKP"]

    /// French Franc
    member self.FRF = self["FRF"]

    /// Pound Sterling
    member self.GBP = self["GBP"]

    /// Lari
    member self.GEL = self["GEL"]

    /// Cedi
    member self.GHC = self["GHC"]

    /// Ghana Cedi
    member self.GHS = self["GHS"]

    /// Gibraltar Pound
    member self.GIP = self["GIP"]

    /// Dalasi
    member self.GMD = self["GMD"]

    /// Guinea Franc
    member self.GNF = self["GNF"]

    /// Greek Drachma
    member self.GRD = self["GRD"]

    /// Quetzal
    member self.GTQ = self["GTQ"]

    /// Guinea-Bissau Peso
    member self.GWP = self["GWP"]

    /// Guyana Dollar
    member self.GYD = self["GYD"]

    /// Hong Kong Dollar
    member self.HKD = self["HKD"]

    /// Lempira
    member self.HNL = self["HNL"]

    /// Croatian Kuna
    member self.HRK = self["HRK"]

    /// Gourde
    member self.HTG = self["HTG"]

    /// Forint
    member self.HUF = self["HUF"]

    /// Rupiah
    member self.IDR = self["IDR"]

    /// Irish Pound
    member self.IEP = self["IEP"]

    /// New Israeli Sheqel
    member self.ILS = self["ILS"]

    /// Indian Rupee
    member self.INR = self["INR"]

    /// Iraqi Dinar
    member self.IQD = self["IQD"]

    /// Iranian Rial
    member self.IRR = self["IRR"]

    /// Iceland Krona
    member self.ISK = self["ISK"]

    /// Italian Lira
    member self.ITL = self["ITL"]

    /// Jamaican Dollar
    member self.JMD = self["JMD"]

    /// Jordanian Dinar
    member self.JOD = self["JOD"]

    /// Yen
    member self.JPY = self["JPY"]

    /// Kenyan Shilling
    member self.KES = self["KES"]

    /// Som
    member self.KGS = self["KGS"]

    /// Riel
    member self.KHR = self["KHR"]

    /// Comoro Franc
    member self.KMF = self["KMF"]

    /// North Korean Won
    member self.KPW = self["KPW"]

    /// Won
    member self.KRW = self["KRW"]

    /// Kuwaiti Dinar
    member self.KWD = self["KWD"]

    /// Cayman Islands Dollar
    member self.KYD = self["KYD"]

    /// Tenge
    member self.KZT = self["KZT"]

    /// Kip
    member self.LAK = self["LAK"]

    /// Lebanese Pound
    member self.LBP = self["LBP"]

    /// Sri Lanka Rupee
    member self.LKR = self["LKR"]

    /// Liberian Dollar
    member self.LRD = self["LRD"]

    /// Loti
    member self.LSL = self["LSL"]

    /// Lithuanian Litas
    member self.LTL = self["LTL"]

    /// Luxembourg Franc
    member self.LUF = self["LUF"]

    /// Latvian Lats
    member self.LVL = self["LVL"]

    /// Libyan Dinar
    member self.LYD = self["LYD"]

    /// Moroccan Dirham
    member self.MAD = self["MAD"]

    /// Moldovan Leu
    member self.MDL = self["MDL"]

    /// Malagasy Ariary
    member self.MGA = self["MGA"]

    /// Malagasy Franc
    member self.MGF = self["MGF"]

    /// Denar
    member self.MKD = self["MKD"]

    /// Mali Franc
    member self.MLF = self["MLF"]

    /// Kyat
    member self.MMK = self["MMK"]

    /// Tugrik
    member self.MNT = self["MNT"]

    /// Pataca
    member self.MOP = self["MOP"]

    /// Ouguiya
    member self.MRO = self["MRO"]

    /// Ouguiya
    member self.MRU = self["MRU"]

    /// Maltese Lira
    member self.MTL = self["MTL"]

    /// Mauritius Rupee
    member self.MUR = self["MUR"]

    /// Rufiyaa
    member self.MVR = self["MVR"]

    /// Kwacha
    member self.MWK = self["MWK"]

    /// Mexican Peso
    member self.MXN = self["MXN"]

    /// Mexican Unidad de Inversion (UDI)
    member self.MXV = self["MXV"]

    /// Malaysian Ringgit
    member self.MYR = self["MYR"]

    /// Mozambique Metical
    member self.MZM = self["MZM"]

    /// Metical
    member self.MZN = self["MZN"]

    /// Namibia Dollar
    member self.NAD = self["NAD"]

    /// Naira
    member self.NGN = self["NGN"]

    /// Nicaraguan Cordoba
    member self.NIC = self["NIC"]

    /// Cordoba Oro
    member self.NIO = self["NIO"]

    /// Netherlands Guilder
    member self.NLG = self["NLG"]

    /// Norwegian Krone
    member self.NOK = self["NOK"]

    /// Nepalese Rupee
    member self.NPR = self["NPR"]

    /// New Zealand Dollar
    member self.NZD = self["NZD"]

    /// Rial Omani
    member self.OMR = self["OMR"]

    /// Balboa
    member self.PAB = self["PAB"]

    /// Nuevo Sol
    member self.PEN = self["PEN"]

    /// Kina
    member self.PGK = self["PGK"]

    /// Philippine Peso
    member self.PHP = self["PHP"]

    /// Pakistan Rupee
    member self.PKR = self["PKR"]

    /// Zloty
    member self.PLN = self["PLN"]

    /// Portuguese Escudo
    member self.PTE = self["PTE"]

    /// Guarani
    member self.PYG = self["PYG"]

    /// Qatari Rial
    member self.QAR = self["QAR"]

    /// Romanian Old Leu
    member self.ROL = self["ROL"]

    /// New Leu
    member self.RON = self["RON"]

    /// Serbian Dinar
    member self.RSD = self["RSD"]

    /// Russian Rouble
    member self.RUB = self["RUB"]

    /// Rwanda Franc
    member self.RWF = self["RWF"]

    /// Saudi Riyal
    member self.SAR = self["SAR"]

    /// Solomon Islands Dollar
    member self.SBD = self["SBD"]

    /// Seychelles Rupee
    member self.SCR = self["SCR"]

    /// Sudanese Dinar
    member self.SDD = self["SDD"]

    /// Sudanese Pound
    member self.SDG = self["SDG"]

    /// Sudanese Pound
    member self.SDP = self["SDP"]

    /// Swedish Krona
    member self.SEK = self["SEK"]

    /// Singapore Dollar
    member self.SGD = self["SGD"]

    /// Saint Helena Pound
    member self.SHP = self["SHP"]

    /// Slovenian Tolar
    member self.SIT = self["SIT"]

    /// Slovak Koruna
    member self.SKK = self["SKK"]

    /// Leone
    member self.SLL = self["SLL"]

    /// Somali Shilling
    member self.SOS = self["SOS"]

    /// Surinam Dollar
    member self.SRD = self["SRD"]

    /// Suriname Guilder
    member self.SRG = self["SRG"]

    /// Dobra
    member self.STD = self["STD"]

    /// El Salvador Colon
    member self.SVC = self["SVC"]

    /// Syrian Pound
    member self.SYP = self["SYP"]

    /// Lilangeni
    member self.SZL = self["SZL"]

    /// Baht
    member self.THB = self["THB"]

    /// Tajik Rouble
    member self.TJR = self["TJR"]

    /// Somoni
    member self.TJS = self["TJS"]

    /// Manat
    member self.TMM = self["TMM"]

    /// Manat
    member self.TMT = self["TMT"]

    /// Tunisian Dinar
    member self.TND = self["TND"]

    /// Pa'anga
    member self.TOP = self["TOP"]

    /// Turkish Lira
    member self.TRY = self["TRY"]

    /// Trinidad and Tobago Dollar
    member self.TTD = self["TTD"]

    /// New Taiwan Dollar
    member self.TWD = self["TWD"]

    /// Tanzanian Shilling
    member self.TZS = self["TZS"]

    /// Hryvnia
    member self.UAH = self["UAH"]

    /// Uganda Shilling
    member self.UGX = self["UGX"]

    /// US Dollar
    member self.USD = self["USD"]

    /// US Dollar (Next day)
    member self.USN = self["USN"]

    /// US Dollar (Same day)
    member self.USS = self["USS"]

    /// Uruguay Peso en Unidades Indexadas
    member self.UYI = self["UYI"]

    /// Peso Uruguayo
    member self.UYU = self["UYU"]

    /// Uzbekistan Sum
    member self.UZS = self["UZS"]

    /// Venezuela Bolívar
    member self.VEB = self["VEB"]

    /// Bolivar Fuerte
    member self.VEF = self["VEF"]

    /// Bolivar Soberano
    member self.VES = self["VES"]

    /// Bolivar Soberano
    member self.VED = self["VED"]

    /// Dong
    member self.VND = self["VND"]

    /// Vatu
    member self.VUV = self["VUV"]

    /// Tala
    member self.WST = self["WST"]

    /// Yemeni Rial
    member self.YER = self["YER"]

    /// Yugoslavian Dinar
    member self.YUM = self["YUM"]

    /// Rand
    member self.ZAR = self["ZAR"]

    /// Kwacha (old)
    member self.ZMK = self["ZMK"]

    /// Zambian Kwacha
    member self.ZMW = self["ZMW"]

    /// Zimbabwe Dollar
    member self.ZWD = self["ZWD"]

    /// Zimbabwe Dollar
    member self.ZWL = self["ZWL"]

    /// CFA Franc BEAC
    member self.XAF = self["XAF"]

    /// East Caribbean Dollar
    member self.XCD = self["XCD"]

    /// SDR
    member self.XDR = self["XDR"]

    /// Gold-Franc
    member self.XFO = self["XFO"]

    /// UIC-Franc
    member self.XFU = self["XFU"]

    /// CFA Franc BCEAO
    member self.XOF = self["XOF"]

    /// CFP Franc
    member self.XPF = self["XPF"]

    /// Code for testing purposes
    member self.XTS = self["XTS"]

    /// No currency
    member self.XXX = self["XXX"]

    /// Silver
    member self.XAG = self["XAG"]

    /// Gold
    member self.XAU = self["XAU"]

    /// Palladium
    member self.XPD = self["XPD"]

    /// Platinum
    member self.XPT = self["XPT"]

    /// Sistema Unitario de Compensación Regional
    member self.XSU = self["XSU"]
